import { Student, StudentListData } from '@repo/shared/types';

export const students: Student[] = [
  {
    id: 1,
    name: '전준연',
    sex: 'MAN',
    email: 's24070@gsm.hs.kr',
    grade: 2,
    classNum: 4,
    number: 15,
    studentNumber: 2415,
    major: 'AI',
    role: 'STUDENT_COUNCIL',
    dormitoryFloor: 3,
    dormitoryRoom: 316,
    isLeaveSchool: false,
    majorClub: { id: 1, name: 'AI개발동아리', type: 'MAJOR_CLUB' },
    jobClub: { id: 2, name: 'AI연구동아리', type: 'JOB_CLUB' },
    autonomousClub: { id: 3, name: '학생회', type: 'AUTONOMOUS_CLUB' },
  },
  {
    id: 2,
    name: '정효주',
    sex: 'WOMAN',
    email: 's24015@gsm.hs.kr',
    grade: 2,
    classNum: 2,
    number: 15,
    studentNumber: 2215,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 502,
    isLeaveSchool: false,
    majorClub: { id: 4, name: 'SW개발동아리', type: 'MAJOR_CLUB' },
    jobClub: { id: 5, name: '웹개발동아리', type: 'JOB_CLUB' },
    autonomousClub: { id: 6, name: '독서동아리', type: 'AUTONOMOUS_CLUB' },
  },
  {
    id: 3,
    name: '김지훈',
    sex: 'MAN',
    email: 's24021@gsm.hs.kr',
    grade: 2,
    classNum: 3,
    number: 4,
    studentNumber: 2304,
    major: 'SMART_IOT',
    role: 'DORMITORY_MANAGER',
    dormitoryFloor: 4,
    dormitoryRoom: 410,
    isLeaveSchool: true,
    majorClub: { id: 7, name: 'IOT개발동아리', type: 'MAJOR_CLUB' },
    jobClub: { id: 8, name: '임베디드동아리', type: 'JOB_CLUB' },
    autonomousClub: { id: 9, name: '기숙사자치회', type: 'AUTONOMOUS_CLUB' },
  },
  {
    id: 4,
    name: '이서연',
    sex: 'WOMAN',
    email: 's24032@gsm.hs.kr',
    grade: 1,
    classNum: 1,
    number: 8,
    studentNumber: 1108,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 510,
    isLeaveSchool: false,
    majorClub: { id: 10, name: '앱개발동아리', type: 'MAJOR_CLUB' },
    jobClub: { id: 11, name: '프론트엔드동아리', type: 'JOB_CLUB' },
    autonomousClub: { id: 12, name: '음악동아리', type: 'AUTONOMOUS_CLUB' },
  },
  {
    id: 5,
    name: '박민수',
    sex: 'MAN',
    email: 's24045@gsm.hs.kr',
    grade: 3,
    classNum: 2,
    number: 12,
    studentNumber: 3212,
    major: 'AI',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 3,
    dormitoryRoom: 308,
    isLeaveSchool: false,
    majorClub: { id: 13, name: 'ML동아리', type: 'MAJOR_CLUB' },
    jobClub: { id: 14, name: '데이터분석동아리', type: 'JOB_CLUB' },
    autonomousClub: { id: 15, name: '봉사동아리', type: 'AUTONOMOUS_CLUB' },
  },
  {
    id: 6,
    name: '최유진',
    sex: 'WOMAN',
    email: 's24056@gsm.hs.kr',
    grade: 1,
    classNum: 3,
    number: 3,
    studentNumber: 1303,
    major: 'SMART_IOT',
    role: 'STUDENT_COUNCIL',
    dormitoryFloor: 5,
    dormitoryRoom: 515,
    isLeaveSchool: false,
    majorClub: { id: 16, name: '로봇공학동아리', type: 'MAJOR_CLUB' },
    jobClub: { id: 17, name: '하드웨어동아리', type: 'JOB_CLUB' },
    autonomousClub: { id: 3, name: '학생회', type: 'AUTONOMOUS_CLUB' },
  },
  {
    id: 7,
    name: '김태현',
    sex: 'MAN',
    email: 's24067@gsm.hs.kr',
    grade: 2,
    classNum: 1,
    number: 7,
    studentNumber: 2107,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 4,
    dormitoryRoom: 405,
    isLeaveSchool: false,
    majorClub: { id: 18, name: '백엔드동아리', type: 'MAJOR_CLUB' },
    jobClub: { id: 19, name: '클라우드동아리', type: 'JOB_CLUB' },
    autonomousClub: { id: 20, name: '운동동아리', type: 'AUTONOMOUS_CLUB' },
  },
  {
    id: 8,
    name: '이수빈',
    sex: 'WOMAN',
    email: 's24078@gsm.hs.kr',
    grade: 3,
    classNum: 4,
    number: 11,
    studentNumber: 3411,
    major: 'AI',
    role: 'DORMITORY_MANAGER',
    dormitoryFloor: 5,
    dormitoryRoom: 520,
    isLeaveSchool: false,
    majorClub: { id: 21, name: '딥러닝동아리', type: 'MAJOR_CLUB' },
    jobClub: { id: 22, name: 'CV동아리', type: 'JOB_CLUB' },
    autonomousClub: { id: 9, name: '기숙사자치회', type: 'AUTONOMOUS_CLUB' },
  },
  {
    id: 9,
    name: '정우성',
    sex: 'MAN',
    email: 's24089@gsm.hs.kr',
    grade: 1,
    classNum: 2,
    number: 5,
    studentNumber: 1205,
    major: 'SMART_IOT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 3,
    dormitoryRoom: 312,
    isLeaveSchool: false,
    majorClub: { id: 23, name: '센서동아리', type: 'MAJOR_CLUB' },
    jobClub: { id: 24, name: 'Arduino동아리', type: 'JOB_CLUB' },
    autonomousClub: { id: 25, name: '게임동아리', type: 'AUTONOMOUS_CLUB' },
  },
  {
    id: 10,
    name: '한지민',
    sex: 'WOMAN',
    email: 's24090@gsm.hs.kr',
    grade: 2,
    classNum: 3,
    number: 9,
    studentNumber: 2309,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 508,
    isLeaveSchool: false,
    majorClub: { id: 26, name: '보안동아리', type: 'MAJOR_CLUB' },
    jobClub: { id: 27, name: '해킹동아리', type: 'JOB_CLUB' },
    autonomousClub: { id: 28, name: '영화동아리', type: 'AUTONOMOUS_CLUB' },
  },
  {
    id: 11,
    name: '구본준',
    sex: 'MAN',
    email: 's24101@gsm.hs.kr',
    grade: 3,
    classNum: 1,
    number: 2,
    studentNumber: 3102,
    major: 'AI',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 4,
    dormitoryRoom: 415,
    isLeaveSchool: false,
    majorClub: { id: 29, name: 'NLP동아리', type: 'MAJOR_CLUB' },
    jobClub: { id: 30, name: '챗봇동아리', type: 'JOB_CLUB' },
    autonomousClub: { id: 31, name: '사진동아리', type: 'AUTONOMOUS_CLUB' },
  },
  {
    id: 12,
    name: '송민아',
    sex: 'WOMAN',
    email: 's24112@gsm.hs.kr',
    grade: 1,
    classNum: 4,
    number: 14,
    studentNumber: 1414,
    major: 'SMART_IOT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 525,
    isLeaveSchool: false,
    majorClub: { id: 32, name: '드론동아리', type: 'MAJOR_CLUB' },
    jobClub: { id: 33, name: '3D프린팅동아리', type: 'JOB_CLUB' },
    autonomousClub: { id: 34, name: '요리동아리', type: 'AUTONOMOUS_CLUB' },
  },
  {
    id: 13,
    name: '오준혁',
    sex: 'MAN',
    email: 's24123@gsm.hs.kr',
    grade: 2,
    classNum: 2,
    number: 6,
    studentNumber: 2206,
    major: 'SW_DEVELOPMENT',
    role: 'STUDENT_COUNCIL',
    dormitoryFloor: 3,
    dormitoryRoom: 320,
    isLeaveSchool: false,
    majorClub: { id: 35, name: '게임개발동아리', type: 'MAJOR_CLUB' },
    jobClub: { id: 36, name: 'Unity동아리', type: 'JOB_CLUB' },
    autonomousClub: { id: 3, name: '학생회', type: 'AUTONOMOUS_CLUB' },
  },
  {
    id: 14,
    name: '김하늘',
    sex: 'WOMAN',
    email: 's24134@gsm.hs.kr',
    grade: 3,
    classNum: 3,
    number: 10,
    studentNumber: 3310,
    major: 'AI',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 530,
    isLeaveSchool: true,
    majorClub: { id: 37, name: '강화학습동아리', type: 'MAJOR_CLUB' },
    jobClub: { id: 38, name: '로보틱스동아리', type: 'JOB_CLUB' },
    autonomousClub: { id: 39, name: '댄스동아리', type: 'AUTONOMOUS_CLUB' },
  },
  {
    id: 15,
    name: '이동현',
    sex: 'MAN',
    email: 's24145@gsm.hs.kr',
    grade: 1,
    classNum: 1,
    number: 13,
    studentNumber: 1113,
    major: 'SMART_IOT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 4,
    dormitoryRoom: 420,
    isLeaveSchool: false,
    majorClub: { id: 40, name: '스마트홈동아리', type: 'MAJOR_CLUB' },
    jobClub: { id: 41, name: 'IoT플랫폼동아리', type: 'JOB_CLUB' },
    autonomousClub: { id: 42, name: '밴드동아리', type: 'AUTONOMOUS_CLUB' },
  },
];

export const demoStudents: StudentListData = {
  totalPages: Math.ceil(students.length / 10),
  totalElements: students.length,
  students,
};
