import { Student } from '@/entities/student';

export const demoStudents: Student[] = [
  {
    studentId: 1,
    name: '김철수',
    sex: 'MAN',
    email: 'chulsoo@gsm.hs.kr',
    grade: 1,
    classNum: 1,
    number: 1,
    studentNumber: 1101,
    major: 'SW',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 3,
    dormitoryRoom: 301,
    isLeaveSchool: false,
  },
  {
    studentId: 2,
    name: '김영희',
    sex: 'WOMAN',
    email: 'yonghee@gsm.hs.kr',
    grade: 2,
    classNum: 2,
    number: 2,
    studentNumber: 2202,
    major: 'SW',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 4,
    dormitoryRoom: 402,
    isLeaveSchool: false,
  },
  {
    studentId: 3,
    name: '김민수',
    sex: 'MAN',
    email: 'minsoo@gsm.hs.kr',
    grade: 3,
    classNum: 3,
    number: 3,
    studentNumber: 3303,
    major: 'SW',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 503,
    isLeaveSchool: false,
  },
];
