import { Student, StudentListData } from '@/entities/student';

export const students: Student[] = [
  {
    id: 1,
    name: '전준연',
    sex: 'MAN',
    email: 's24070@gsm.hs.kr',
    grade: 2,
    classNum: 4,
    number: 15,
    studentNumber: 2415,
    major: 'AI',
    role: 'STUDENT_COUNCIL',
    dormitoryFloor: 3,
    dormitoryRoom: 316,
    isLeaveSchool: false,
    majorClub: { id: 1, name: 'AI개발동아리', type: 'MAJOR' },
    jobClub: { id: 2, name: 'AI연구동아리', type: 'JOB' },
    autonomousClub: { id: 3, name: '학생회', type: 'AUTONOMOUS' },
  },
  {
    id: 2,
    name: '정효주',
    sex: 'WOMAN',
    email: 's24015@gsm.hs.kr',
    grade: 2,
    classNum: 2,
    number: 15,
    studentNumber: 2215,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 502,
    isLeaveSchool: false,
    majorClub: { id: 4, name: 'SW개발동아리', type: 'MAJOR' },
    jobClub: { id: 5, name: '웹개발동아리', type: 'JOB' },
    autonomousClub: { id: 6, name: '독서동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 3,
    name: '김지훈',
    sex: 'MAN',
    email: 's24021@gsm.hs.kr',
    grade: 2,
    classNum: 3,
    number: 4,
    studentNumber: 2304,
    major: 'SMART_IOT',
    role: 'DORMITORY_MANAGER',
    dormitoryFloor: 4,
    dormitoryRoom: 410,
    isLeaveSchool: true,
    majorClub: { id: 7, name: 'IOT개발동아리', type: 'MAJOR' },
    jobClub: { id: 8, name: '임베디드동아리', type: 'JOB' },
    autonomousClub: { id: 9, name: '기숙사자치회', type: 'AUTONOMOUS' },
  },
  {
    id: 4,
    name: '이서연',
    sex: 'WOMAN',
    email: 's24032@gsm.hs.kr',
    grade: 1,
    classNum: 1,
    number: 8,
    studentNumber: 1108,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 510,
    isLeaveSchool: false,
    majorClub: { id: 10, name: '앱개발동아리', type: 'MAJOR' },
    jobClub: { id: 11, name: '프론트엔드동아리', type: 'JOB' },
    autonomousClub: { id: 12, name: '음악동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 5,
    name: '박민수',
    sex: 'MAN',
    email: 's24045@gsm.hs.kr',
    grade: 3,
    classNum: 2,
    number: 12,
    studentNumber: 3212,
    major: 'AI',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 3,
    dormitoryRoom: 308,
    isLeaveSchool: false,
    majorClub: { id: 13, name: 'ML동아리', type: 'MAJOR' },
    jobClub: { id: 14, name: '데이터분석동아리', type: 'JOB' },
    autonomousClub: { id: 15, name: '봉사동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 6,
    name: '최유진',
    sex: 'WOMAN',
    email: 's24056@gsm.hs.kr',
    grade: 1,
    classNum: 3,
    number: 3,
    studentNumber: 1303,
    major: 'SMART_IOT',
    role: 'STUDENT_COUNCIL',
    dormitoryFloor: 5,
    dormitoryRoom: 515,
    isLeaveSchool: false,
    majorClub: { id: 16, name: '로봇공학동아리', type: 'MAJOR' },
    jobClub: { id: 17, name: '하드웨어동아리', type: 'JOB' },
    autonomousClub: { id: 3, name: '학생회', type: 'AUTONOMOUS' },
  },
  {
    id: 7,
    name: '김태현',
    sex: 'MAN',
    email: 's24067@gsm.hs.kr',
    grade: 2,
    classNum: 1,
    number: 7,
    studentNumber: 2107,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 4,
    dormitoryRoom: 405,
    isLeaveSchool: false,
    majorClub: { id: 18, name: '백엔드동아리', type: 'MAJOR' },
    jobClub: { id: 19, name: '클라우드동아리', type: 'JOB' },
    autonomousClub: { id: 20, name: '운동동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 8,
    name: '이수빈',
    sex: 'WOMAN',
    email: 's24078@gsm.hs.kr',
    grade: 3,
    classNum: 4,
    number: 11,
    studentNumber: 3411,
    major: 'AI',
    role: 'DORMITORY_MANAGER',
    dormitoryFloor: 5,
    dormitoryRoom: 520,
    isLeaveSchool: false,
    majorClub: { id: 21, name: '딥러닝동아리', type: 'MAJOR' },
    jobClub: { id: 22, name: 'CV동아리', type: 'JOB' },
    autonomousClub: { id: 9, name: '기숙사자치회', type: 'AUTONOMOUS' },
  },
  {
    id: 9,
    name: '정우성',
    sex: 'MAN',
    email: 's24089@gsm.hs.kr',
    grade: 1,
    classNum: 2,
    number: 5,
    studentNumber: 1205,
    major: 'SMART_IOT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 3,
    dormitoryRoom: 312,
    isLeaveSchool: false,
    majorClub: { id: 23, name: '센서동아리', type: 'MAJOR' },
    jobClub: { id: 24, name: 'Arduino동아리', type: 'JOB' },
    autonomousClub: { id: 25, name: '게임동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 10,
    name: '한지민',
    sex: 'WOMAN',
    email: 's24090@gsm.hs.kr',
    grade: 2,
    classNum: 3,
    number: 9,
    studentNumber: 2309,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 508,
    isLeaveSchool: false,
    majorClub: { id: 26, name: '보안동아리', type: 'MAJOR' },
    jobClub: { id: 27, name: '해킹동아리', type: 'JOB' },
    autonomousClub: { id: 28, name: '영화동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 11,
    name: '구본준',
    sex: 'MAN',
    email: 's24101@gsm.hs.kr',
    grade: 3,
    classNum: 1,
    number: 2,
    studentNumber: 3102,
    major: 'AI',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 4,
    dormitoryRoom: 415,
    isLeaveSchool: false,
    majorClub: { id: 29, name: 'NLP동아리', type: 'MAJOR' },
    jobClub: { id: 30, name: '챗봇동아리', type: 'JOB' },
    autonomousClub: { id: 31, name: '사진동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 12,
    name: '송민아',
    sex: 'WOMAN',
    email: 's24112@gsm.hs.kr',
    grade: 1,
    classNum: 4,
    number: 14,
    studentNumber: 1414,
    major: 'SMART_IOT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 525,
    isLeaveSchool: false,
    majorClub: { id: 32, name: '드론동아리', type: 'MAJOR' },
    jobClub: { id: 33, name: '3D프린팅동아리', type: 'JOB' },
    autonomousClub: { id: 34, name: '요리동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 13,
    name: '오준혁',
    sex: 'MAN',
    email: 's24123@gsm.hs.kr',
    grade: 2,
    classNum: 2,
    number: 6,
    studentNumber: 2206,
    major: 'SW_DEVELOPMENT',
    role: 'STUDENT_COUNCIL',
    dormitoryFloor: 3,
    dormitoryRoom: 320,
    isLeaveSchool: false,
    majorClub: { id: 35, name: '게임개발동아리', type: 'MAJOR' },
    jobClub: { id: 36, name: 'Unity동아리', type: 'JOB' },
    autonomousClub: { id: 3, name: '학생회', type: 'AUTONOMOUS' },
  },
  {
    id: 14,
    name: '김하늘',
    sex: 'WOMAN',
    email: 's24134@gsm.hs.kr',
    grade: 3,
    classNum: 3,
    number: 10,
    studentNumber: 3310,
    major: 'AI',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 530,
    isLeaveSchool: true,
    majorClub: { id: 37, name: '강화학습동아리', type: 'MAJOR' },
    jobClub: { id: 38, name: '로보틱스동아리', type: 'JOB' },
    autonomousClub: { id: 39, name: '댄스동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 15,
    name: '이동현',
    sex: 'MAN',
    email: 's24145@gsm.hs.kr',
    grade: 1,
    classNum: 1,
    number: 13,
    studentNumber: 1113,
    major: 'SMART_IOT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 4,
    dormitoryRoom: 420,
    isLeaveSchool: false,
    majorClub: { id: 40, name: '스마트홈동아리', type: 'MAJOR' },
    jobClub: { id: 41, name: 'IoT플랫폼동아리', type: 'JOB' },
    autonomousClub: { id: 42, name: '밴드동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 16,
    name: '박서윤',
    sex: 'WOMAN',
    email: 's24156@gsm.hs.kr',
    grade: 2,
    classNum: 4,
    number: 1,
    studentNumber: 2401,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 535,
    isLeaveSchool: false,
    majorClub: { id: 43, name: 'DevOps동아리', type: 'MAJOR' },
    jobClub: { id: 44, name: 'CI/CD동아리', type: 'JOB' },
    autonomousClub: { id: 45, name: '봉사동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 17,
    name: '최준서',
    sex: 'MAN',
    email: 's24167@gsm.hs.kr',
    grade: 3,
    classNum: 2,
    number: 8,
    studentNumber: 3208,
    major: 'AI',
    role: 'DORMITORY_MANAGER',
    dormitoryFloor: 3,
    dormitoryRoom: 325,
    isLeaveSchool: false,
    majorClub: { id: 46, name: 'MLOps동아리', type: 'MAJOR' },
    jobClub: { id: 47, name: '모델배포동아리', type: 'JOB' },
    autonomousClub: { id: 9, name: '기숙사자치회', type: 'AUTONOMOUS' },
  },
  {
    id: 18,
    name: '정다은',
    sex: 'WOMAN',
    email: 's24178@gsm.hs.kr',
    grade: 1,
    classNum: 3,
    number: 16,
    studentNumber: 1316,
    major: 'SMART_IOT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 540,
    isLeaveSchool: false,
    majorClub: { id: 48, name: '웨어러블동아리', type: 'MAJOR' },
    jobClub: { id: 49, name: '헬스케어동아리', type: 'JOB' },
    autonomousClub: { id: 50, name: '독서동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 19,
    name: '윤성민',
    sex: 'MAN',
    email: 's24189@gsm.hs.kr',
    grade: 2,
    classNum: 1,
    number: 11,
    studentNumber: 2111,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 4,
    dormitoryRoom: 425,
    isLeaveSchool: false,
    majorClub: { id: 51, name: '모바일동아리', type: 'MAJOR' },
    jobClub: { id: 52, name: 'Flutter동아리', type: 'JOB' },
    autonomousClub: { id: 53, name: '축구동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 20,
    name: '김예진',
    sex: 'WOMAN',
    email: 's24190@gsm.hs.kr',
    grade: 3,
    classNum: 4,
    number: 4,
    studentNumber: 3404,
    major: 'AI',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 545,
    isLeaveSchool: false,
    majorClub: { id: 54, name: '음성인식동아리', type: 'MAJOR' },
    jobClub: { id: 55, name: 'TTS동아리', type: 'JOB' },
    autonomousClub: { id: 56, name: '연극동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 21,
    name: '장현우',
    sex: 'MAN',
    email: 's24201@gsm.hs.kr',
    grade: 1,
    classNum: 2,
    number: 9,
    studentNumber: 1209,
    major: 'SMART_IOT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 3,
    dormitoryRoom: 330,
    isLeaveSchool: false,
    majorClub: { id: 57, name: '자동화동아리', type: 'MAJOR' },
    jobClub: { id: 58, name: 'PLC동아리', type: 'JOB' },
    autonomousClub: { id: 59, name: '농구동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 22,
    name: '신유나',
    sex: 'WOMAN',
    email: 's24212@gsm.hs.kr',
    grade: 2,
    classNum: 3,
    number: 17,
    studentNumber: 2317,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 550,
    isLeaveSchool: false,
    majorClub: { id: 60, name: 'UI/UX동아리', type: 'MAJOR' },
    jobClub: { id: 61, name: '디자인동아리', type: 'JOB' },
    autonomousClub: { id: 62, name: '미술동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 23,
    name: '임재혁',
    sex: 'MAN',
    email: 's24223@gsm.hs.kr',
    grade: 3,
    classNum: 1,
    number: 6,
    studentNumber: 3106,
    major: 'AI',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 4,
    dormitoryRoom: 430,
    isLeaveSchool: true,
    majorClub: { id: 63, name: 'GAN동아리', type: 'MAJOR' },
    jobClub: { id: 64, name: '이미지생성동아리', type: 'JOB' },
    autonomousClub: { id: 65, name: '바둑동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 24,
    name: '홍수아',
    sex: 'WOMAN',
    email: 's24234@gsm.hs.kr',
    grade: 1,
    classNum: 4,
    number: 2,
    studentNumber: 1402,
    major: 'SMART_IOT',
    role: 'STUDENT_COUNCIL',
    dormitoryFloor: 5,
    dormitoryRoom: 555,
    isLeaveSchool: false,
    majorClub: { id: 66, name: '임베디드시스템동아리', type: 'MAJOR' },
    jobClub: { id: 67, name: 'RTOS동아리', type: 'JOB' },
    autonomousClub: { id: 3, name: '학생회', type: 'AUTONOMOUS' },
  },
  {
    id: 25,
    name: '강민재',
    sex: 'MAN',
    email: 's24245@gsm.hs.kr',
    grade: 2,
    classNum: 2,
    number: 18,
    studentNumber: 2218,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 3,
    dormitoryRoom: 335,
    isLeaveSchool: false,
    majorClub: { id: 68, name: '오픈소스동아리', type: 'MAJOR' },
    jobClub: { id: 69, name: 'Git동아리', type: 'JOB' },
    autonomousClub: { id: 70, name: '토론동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 26,
    name: '김도현',
    sex: 'MAN',
    email: 's24256@gsm.hs.kr',
    grade: 1,
    classNum: 3,
    number: 7,
    studentNumber: 1307,
    major: 'AI',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 4,
    dormitoryRoom: 401,
    isLeaveSchool: false,
    majorClub: { id: 71, name: '데이터과학동아리', type: 'MAJOR' },
    jobClub: { id: 72, name: 'RPA동아리', type: 'JOB' },
    autonomousClub: { id: 73, name: '여행동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 27,
    name: '이하은',
    sex: 'WOMAN',
    email: 's24267@gsm.hs.kr',
    grade: 2,
    classNum: 4,
    number: 13,
    studentNumber: 2413,
    major: 'SMART_IOT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 503,
    isLeaveSchool: false,
    majorClub: { id: 74, name: '스마트팩토리동아리', type: 'MAJOR' },
    jobClub: { id: 75, name: 'SCADA동아리', type: 'JOB' },
    autonomousClub: { id: 76, name: '사진동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 28,
    name: '박건우',
    sex: 'MAN',
    email: 's24278@gsm.hs.kr',
    grade: 3,
    classNum: 1,
    number: 19,
    studentNumber: 3119,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 3,
    dormitoryRoom: 305,
    isLeaveSchool: false,
    majorClub: { id: 77, name: '분산시스템동아리', type: 'MAJOR' },
    jobClub: { id: 78, name: 'Kubernetes동아리', type: 'JOB' },
    autonomousClub: { id: 79, name: '독서동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 29,
    name: '최수민',
    sex: 'WOMAN',
    email: 's24289@gsm.hs.kr',
    grade: 1,
    classNum: 2,
    number: 1,
    studentNumber: 1201,
    major: 'AI',
    role: 'STUDENT_COUNCIL',
    dormitoryFloor: 5,
    dormitoryRoom: 507,
    isLeaveSchool: false,
    majorClub: { id: 80, name: '자연어처리동아리', type: 'MAJOR' },
    jobClub: { id: 81, name: '음성인식동아리', type: 'JOB' },
    autonomousClub: { id: 3, name: '학생회', type: 'AUTONOMOUS' },
  },
  {
    id: 30,
    name: '장민준',
    sex: 'MAN',
    email: 's24290@gsm.hs.kr',
    grade: 2,
    classNum: 3,
    number: 20,
    studentNumber: 2320,
    major: 'SMART_IOT',
    role: 'DORMITORY_MANAGER',
    dormitoryFloor: 4,
    dormitoryRoom: 403,
    isLeaveSchool: true,
    majorClub: { id: 82, name: '스마트팜동아리', type: 'MAJOR' },
    jobClub: { id: 83, name: '드론제어동아리', type: 'JOB' },
    autonomousClub: { id: 9, name: '기숙사자치회', type: 'AUTONOMOUS' },
  },
  {
    id: 31,
    name: '조민서',
    sex: 'WOMAN',
    email: 's24301@gsm.hs.kr',
    grade: 1,
    classNum: 1,
    number: 10,
    studentNumber: 1110,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 512,
    isLeaveSchool: false,
    majorClub: { id: 84, name: '웹프레임워크동아리', type: 'MAJOR' },
    jobClub: { id: 85, name: 'React동아리', type: 'JOB' },
    autonomousClub: { id: 86, name: '보드게임동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 32,
    name: '황지후',
    sex: 'MAN',
    email: 's24312@gsm.hs.kr',
    grade: 2,
    classNum: 2,
    number: 2,
    studentNumber: 2202,
    major: 'AI',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 3,
    dormitoryRoom: 314,
    isLeaveSchool: false,
    majorClub: { id: 87, name: '컴퓨터비전동아리', type: 'MAJOR' },
    jobClub: { id: 88, name: 'OpenCV동아리', type: 'JOB' },
    autonomousClub: { id: 89, name: '영화감상동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 33,
    name: '서예은',
    sex: 'WOMAN',
    email: 's24323@gsm.hs.kr',
    grade: 3,
    classNum: 3,
    number: 5,
    studentNumber: 3305,
    major: 'SMART_IOT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 518,
    isLeaveSchool: false,
    majorClub: { id: 90, name: '사물인터넷보안동아리', type: 'MAJOR' },
    jobClub: { id: 91, name: '네트워크보안동아리', type: 'JOB' },
    autonomousClub: { id: 92, name: '등산동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 34,
    name: '문진호',
    sex: 'MAN',
    email: 's24334@gsm.hs.kr',
    grade: 1,
    classNum: 4,
    number: 18,
    studentNumber: 1418,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 4,
    dormitoryRoom: 418,
    isLeaveSchool: false,
    majorClub: { id: 93, name: '알고리즘동아리', type: 'MAJOR' },
    jobClub: { id: 94, name: '코딩테스트동아리', type: 'JOB' },
    autonomousClub: { id: 95, name: '체스동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 35,
    name: '안서현',
    sex: 'WOMAN',
    email: 's24345@gsm.hs.kr',
    grade: 2,
    classNum: 1,
    number: 12,
    studentNumber: 2112,
    major: 'AI',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 522,
    isLeaveSchool: false,
    majorClub: { id: 96, name: '추천시스템동아리', type: 'MAJOR' },
    jobClub: { id: 97, name: '빅데이터동아리', type: 'JOB' },
    autonomousClub: { id: 98, name: '만화동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 36,
    name: '류정민',
    sex: 'MAN',
    email: 's24356@gsm.hs.kr',
    grade: 3,
    classNum: 2,
    number: 3,
    studentNumber: 3203,
    major: 'SMART_IOT',
    role: 'STUDENT_COUNCIL',
    dormitoryFloor: 3,
    dormitoryRoom: 318,
    isLeaveSchool: false,
    majorClub: { id: 99, name: '스마트에너지동아리', type: 'MAJOR' },
    jobClub: { id: 100, name: 'BEMS동아리', type: 'JOB' },
    autonomousClub: { id: 3, name: '학생회', type: 'AUTONOMOUS' },
  },
  {
    id: 37,
    name: '허윤아',
    sex: 'WOMAN',
    email: 's24367@gsm.hs.kr',
    grade: 1,
    classNum: 3,
    number: 14,
    studentNumber: 1314,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 528,
    isLeaveSchool: true,
    majorClub: { id: 101, name: '블록체인동아리', type: 'MAJOR' },
    jobClub: { id: 102, name: '가상화폐동아리', type: 'JOB' },
    autonomousClub: { id: 103, name: '투자동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 38,
    name: '성지훈',
    sex: 'MAN',
    email: 's24378@gsm.hs.kr',
    grade: 2,
    classNum: 4,
    number: 9,
    studentNumber: 2409,
    major: 'AI',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 4,
    dormitoryRoom: 422,
    isLeaveSchool: false,
    majorClub: { id: 104, name: 'AI윤리동아리', type: 'MAJOR' },
    jobClub: { id: 105, name: 'IT정책동아리', type: 'JOB' },
    autonomousClub: { id: 106, name: '시사토론동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 39,
    name: '오채원',
    sex: 'WOMAN',
    email: 's24389@gsm.hs.kr',
    grade: 3,
    classNum: 1,
    number: 1,
    studentNumber: 3101,
    major: 'SMART_IOT',
    role: 'DORMITORY_MANAGER',
    dormitoryFloor: 5,
    dormitoryRoom: 532,
    isLeaveSchool: false,
    majorClub: { id: 107, name: '지능형로봇동아리', type: 'MAJOR' },
    jobClub: { id: 108, name: 'ROS동아리', type: 'JOB' },
    autonomousClub: { id: 9, name: '기숙사자치회', type: 'AUTONOMOUS' },
  },
  {
    id: 40,
    name: '유승호',
    sex: 'MAN',
    email: 's24390@gsm.hs.kr',
    grade: 1,
    classNum: 2,
    number: 17,
    studentNumber: 1217,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 3,
    dormitoryRoom: 322,
    isLeaveSchool: false,
    majorClub: { id: 109, name: '클라우드네이티브동아리', type: 'MAJOR' },
    jobClub: { id: 110, name: 'Docker동아리', type: 'JOB' },
    autonomousClub: { id: 111, name: '요리동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 41,
    name: '손예림',
    sex: 'WOMAN',
    email: 's24401@gsm.hs.kr',
    grade: 2,
    classNum: 3,
    number: 8,
    studentNumber: 2308,
    major: 'AI',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 538,
    isLeaveSchool: false,
    majorClub: { id: 112, name: '생성AI동아리', type: 'MAJOR' },
    jobClub: { id: 113, name: 'LLM동아리', type: 'JOB' },
    autonomousClub: { id: 114, name: '글쓰기동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 42,
    name: '신동엽',
    sex: 'MAN',
    email: 's24412@gsm.hs.kr',
    grade: 3,
    classNum: 4,
    number: 16,
    studentNumber: 3416,
    major: 'SMART_IOT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 4,
    dormitoryRoom: 428,
    isLeaveSchool: false,
    majorClub: { id: 115, name: '자율주행동아리', type: 'MAJOR' },
    jobClub: { id: 116, name: 'LIDAR동아리', type: 'JOB' },
    autonomousClub: { id: 117, name: '자동차동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 43,
    name: '배유나',
    sex: 'WOMAN',
    email: 's24423@gsm.hs.kr',
    grade: 1,
    classNum: 1,
    number: 4,
    studentNumber: 1104,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 542,
    isLeaveSchool: false,
    majorClub: { id: 118, name: '정보보호동아리', type: 'MAJOR' },
    jobClub: { id: 119, name: 'CTF동아리', type: 'JOB' },
    autonomousClub: { id: 120, name: '방탈출동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 44,
    name: '강동원',
    sex: 'MAN',
    email: 's24434@gsm.hs.kr',
    grade: 2,
    classNum: 2,
    number: 11,
    studentNumber: 2211,
    major: 'AI',
    role: 'STUDENT_COUNCIL',
    dormitoryFloor: 3,
    dormitoryRoom: 328,
    isLeaveSchool: false,
    majorClub: { id: 121, name: '메타버스동아리', type: 'MAJOR' },
    jobClub: { id: 122, name: 'VR/AR동아리', type: 'JOB' },
    autonomousClub: { id: 3, name: '학생회', type: 'AUTONOMOUS' },
  },
  {
    id: 45,
    name: '문채원',
    sex: 'WOMAN',
    email: 's24445@gsm.hs.kr',
    grade: 3,
    classNum: 3,
    number: 13,
    studentNumber: 3313,
    major: 'SMART_IOT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 548,
    isLeaveSchool: true,
    majorClub: { id: 123, name: '스마트시티동아리', type: 'MAJOR' },
    jobClub: { id: 124, name: '도시데이터동아리', type: 'JOB' },
    autonomousClub: { id: 125, name: '건축동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 46,
    name: '송중기',
    sex: 'MAN',
    email: 's24456@gsm.hs.kr',
    grade: 1,
    classNum: 4,
    number: 6,
    studentNumber: 1406,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 4,
    dormitoryRoom: 432,
    isLeaveSchool: false,
    majorClub: { id: 126, name: '금융IT동아리', type: 'MAJOR' },
    jobClub: { id: 127, name: '핀테크동아리', type: 'JOB' },
    autonomousClub: { id: 128, name: '경제동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 47,
    name: '임수정',
    sex: 'WOMAN',
    email: 's24467@gsm.hs.kr',
    grade: 2,
    classNum: 1,
    number: 18,
    studentNumber: 2118,
    major: 'AI',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 552,
    isLeaveSchool: false,
    majorClub: { id: 129, name: 'AI의료동아리', type: 'MAJOR' },
    jobClub: { id: 130, name: '의료영상분석동아리', type: 'JOB' },
    autonomousClub: { id: 131, name: '생명과학동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 48,
    name: '노주현',
    sex: 'MAN',
    email: 's24478@gsm.hs.kr',
    grade: 3,
    classNum: 2,
    number: 7,
    studentNumber: 3207,
    major: 'SMART_IOT',
    role: 'DORMITORY_MANAGER',
    dormitoryFloor: 3,
    dormitoryRoom: 332,
    isLeaveSchool: false,
    majorClub: { id: 132, name: '스마트모빌리티동아리', type: 'MAJOR' },
    jobClub: { id: 133, name: '자율주행차동아리', type: 'JOB' },
    autonomousClub: { id: 9, name: '기숙사자치회', type: 'AUTONOMOUS' },
  },
  {
    id: 49,
    name: '천우희',
    sex: 'WOMAN',
    email: 's24489@gsm.hs.kr',
    grade: 1,
    classNum: 3,
    number: 11,
    studentNumber: 1311,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 558,
    isLeaveSchool: false,
    majorClub: { id: 134, name: '이커머스동아리', type: 'MAJOR' },
    jobClub: { id: 135, name: '결제시스템동아리', type: 'JOB' },
    autonomousClub: { id: 136, name: '마케팅동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 50,
    name: '하정우',
    sex: 'MAN',
    email: 's24490@gsm.hs.kr',
    grade: 2,
    classNum: 4,
    number: 5,
    studentNumber: 2405,
    major: 'AI',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 4,
    dormitoryRoom: 438,
    isLeaveSchool: false,
    majorClub: { id: 137, name: 'AI작곡동아리', type: 'MAJOR' },
    jobClub: { id: 138, name: '사운드엔지니어링동아리', type: 'JOB' },
    autonomousClub: { id: 12, name: '음악동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 51,
    name: '이정훈',
    sex: 'MAN',
    email: 's24491@gsm.hs.kr',
    grade: 3,
    classNum: 1,
    number: 12,
    studentNumber: 3112,
    major: 'SMART_IOT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 562,
    isLeaveSchool: false,
    majorClub: { id: 139, name: 'IoT기기동아리', type: 'MAJOR' },
    jobClub: { id: 140, name: 'IoT센서동아리', type: 'JOB' },
    autonomousClub: { id: 141, name: 'IoT기기동아리', type: 'AUTONOMOUS' },
  },
  {
    id: 52,
    name: '김정훈',
    sex: 'MAN',
    email: 's24492@gsm.hs.kr',
    grade: 1,
    classNum: 2,
    number: 13,
    studentNumber: 1213,
    major: 'SW_DEVELOPMENT',
    role: 'GENERAL_STUDENT',
    dormitoryFloor: 5,
    dormitoryRoom: 568,
    isLeaveSchool: false,
    majorClub: { id: 142, name: 'IoT기기동아리', type: 'MAJOR' },
    jobClub: { id: 143, name: 'IoT센서동아리', type: 'JOB' },
    autonomousClub: { id: 144, name: 'IoT기기동아리', type: 'AUTONOMOUS' },
  },
];

export const demoStudents: StudentListData = {
  totalPages: Math.ceil(students.length / 10),
  totalElements: students.length,
  students,
};
